export {
  MEASUREMENT_FIELD_DEFINITIONS,
  MEASUREMENT_FIELD_MAP,
  MEASUREMENT_MANUAL_FIELDS as MEASUREMENT_FIELDS,
  MEASUREMENT_MANUAL_FIELD_KEYS as BODY_FIELD_KEYS,
  MEASUREMENT_MANUAL_FIELD_SECTIONS,
  MEASUREMENT_SECTION_LABELS,
  MEASUREMENT_SOURCE_OPTIONS,
  MEASUREMENT_SOURCE_LABELS,
  MEASUREMENT_SOURCE_VALUES,
  MEASUREMENT_IMPORTED_FIELDS,
  MEASUREMENT_IMPORTED_FIELD_KEYS,
  MEASUREMENT_IMPORTED_COMPOSITION_FIELDS,
  MEASUREMENT_DERIVED_FIELDS,
  MEASUREMENT_DERIVED_FIELD_KEYS,
  MEASUREMENT_FORM_FIELDS,
  MEASUREMENT_FORM_FIELD_KEYS,
  MEASUREMENT_MANUAL_FIELD_KEYS,
  MEASUREMENT_COMPOSITION_SECTION,
  MEASUREMENT_DERIVED_SECTION,
  MEASUREMENT_TREND_FIELD_KEYS,
  MEASUREMENT_DISPLAY_FIELD_KEYS,
  MEASUREMENT_SOURCE_FIELD_KEYS,
  countFilledMeasurementFields,
  computeDerivedMeasurementFields,
  getMeasurementFieldDefinition,
  getMeasurementFieldErrors,
  getMeasurementFieldLabel,
  getMeasurementFieldSourceLabel,
  getMeasurementFieldUnit,
  getMeasurementFieldValue,
  getMeasurementFormState,
  getMeasurementValidationSummary,
  isValidDateKey,
  measurementFormSchema,
  normalizeMeasurementEntry,
  normalizeMeasurementSource,
  normalizeFieldSource,
  prepareMeasurementWritePayload,
  validateMeasurementConsistency,
} from './measurementModel.js';
export { BODY_FIELD_LABELS } from './measurementModel.js';
