export const ROUTES = {
  home: '/',
  auth: '/auth',
  login: '/login',
  signup: '/signup',
  onboarding: '/Onboarding',
  today: '/Today',
  nutrition: '/Nutrition',
  workouts: '/Workouts',
  routines: '/Routines',
  protocols: '/Protocols',
  measurements: '/Measurements',
  labExams: '/LabExams',
  progressReview: '/ProgressReview',
  insights: '/Insights',
  blockReview: '/block-review',
  exercises: '/Exercises',
  progress: '/Progress',
  plan: '/Plan',
  profile: '/Profile',
  goals: '/goals',
  bodyProfile: '/body-profile',
  account: '/account',
  export: '/Export',
  admin: '/AdminPanel',
  myDiet: '/my-diet',
  myWorkout: '/my-workout',
  diary: '/diary',
  progressPhotos: '/progress-photos',
  body: '/body',
  bodyCheckpointNew: '/body/checkpoints/new',
  social: '/social',
  manualWorkout: '/manual-workout',
  prescribedDiet: '/prescribed-diet',
  pricing: '/Pricing',
  prescribedWorkout: '/prescribed-workout',
  coachDashboard: '/coach-dashboard',
  coachStudents: '/coach/students',
  nutritionistDashboard: '/nutritionist-dashboard',
  nutritionistClients: '/nutritionist/clients',
  clinicianDashboard: '/clinician-dashboard',
  clinicianPatients: '/clinician/patients',
  githubPRs: '/github-prs',
  help: '/help',
  blog: '/blog',
  settings: '/Settings',
  storyLanding: '/start',
  shareTarget: '/share-target',
  notifications: '/notifications',
  adminAnalytics: '/AdminPanel/analytics',
  adminViewAs: '/AdminPanel/view-as',
};

/**
 * Default home page per role.
 * In the public MVP, professional routes are gated — all roles land on /Today
 * unless VITE_ENABLE_PRO_ROUTES is enabled (internal/staging builds).
 */
const proRoutesEnabled = true;

export const ROLE_HOME = {
  athlete:      ROUTES.today,
  coach:        proRoutesEnabled ? ROUTES.coachDashboard        : ROUTES.today,
  nutritionist: proRoutesEnabled ? ROUTES.nutritionistDashboard : ROUTES.today,
  clinician:    proRoutesEnabled ? ROUTES.clinicianDashboard    : ROUTES.today,
  admin:        proRoutesEnabled ? ROUTES.admin                 : ROUTES.today,
};

export const LEGACY_ROUTE_REDIRECTS = [
  ['/Landing', ROUTES.home],
  ['/home', ROUTES.home],
  ['/landing', ROUTES.home],
  ['/onboarding', ROUTES.onboarding],
  ['/today', ROUTES.today],
  ['/nutrition', ROUTES.nutrition],
  ['/workouts', ROUTES.workouts],
  ['/routines', ROUTES.routines],
  ['/protocols', ROUTES.protocols],
  ['/measurements', `${ROUTES.measurements}`],
  ['/lab-exams', ROUTES.labExams],
  ['/AtlasAI', ROUTES.progressReview],
  ['/atlas-ai', ROUTES.progressReview],
  ['/insights', ROUTES.insights],
  ['/exercises', ROUTES.exercises],
  ['/progress', ROUTES.progress],
  ['/profile', ROUTES.profile],
  ['/export', ROUTES.export],
  ['/admin', ROUTES.admin],
  ['/pricing', ROUTES.pricing],
  ['/Social', ROUTES.social],
];
