export const ROUTES = {
  home: '/',
  auth: '/auth',
  login: '/login',
  signup: '/signup',
  onboarding: '/Onboarding',
  today: '/Today',
  nutrition: '/Nutrition',
  workouts: '/Workouts',
  routines: '/Routines',
  protocols: '/Protocols',
  measurements: '/Measurements',
  labExams: '/LabExams',
  atlasAI: '/AtlasAI',
  insights: '/Insights',
  exercises: '/Exercises',
  progress: '/Progress',
  profile: '/Profile',
  export: '/Export',
  admin: '/AdminPanel',
  myDiet: '/my-diet',
  myWorkout: '/my-workout',
  diary: '/diary',
  progressPhotos: '/progress-photos',
  social: '/social',
  manualWorkout: '/manual-workout',
  prescribedDiet: '/prescribed-diet',
  pricing: '/Pricing',
  prescribedWorkout: '/prescribed-workout',
  coachDashboard: '/coach-dashboard',
  coachStudents: '/coach/students',
  nutritionistDashboard: '/nutritionist-dashboard',
  nutritionistClients: '/nutritionist/clients',
  clinicianDashboard: '/clinician-dashboard',
  clinicianPatients: '/clinician/patients',
  githubPRs: '/github-prs',
  help: '/help',
  blog: '/blog',
  settings: '/Settings',
};

export const ROLE_HOME = {
  athlete: ROUTES.today,
  coach: ROUTES.coachDashboard,
  nutritionist: ROUTES.nutritionistDashboard,
  clinician: ROUTES.clinicianDashboard,
  admin: ROUTES.admin,
};

export const LEGACY_ROUTE_REDIRECTS = [
  ['/Landing', ROUTES.home],
  ['/home', ROUTES.home],
  ['/landing', ROUTES.home],
  ['/onboarding', ROUTES.onboarding],
  ['/today', ROUTES.today],
  ['/nutrition', ROUTES.nutrition],
  ['/workouts', ROUTES.workouts],
  ['/routines', ROUTES.routines],
  ['/protocols', ROUTES.protocols],
  ['/measurements', ROUTES.measurements],
  ['/lab-exams', ROUTES.labExams],
  ['/atlas-ai', ROUTES.atlasAI],
  ['/insights', ROUTES.insights],
  ['/exercises', ROUTES.exercises],
  ['/progress', ROUTES.progress],
  ['/profile', ROUTES.profile],
  ['/export', ROUTES.export],
  ['/admin', ROUTES.admin],
  ['/pricing', ROUTES.pricing],
  ['/Social', ROUTES.social],
];
