# Supabase Configuration File
# https://supabase.com/docs/guides/cli/config

[functions.auth-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.food-search]
verify_jwt = false

[functions.send-email-v2]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
