export type VisualRouteAuth = 'public' | 'user';
export type VisualRouteCategory = 'public' | 'authenticated' | 'hidden-internal';

export type VisualAuditRoute = {
  slug: string;
  path: string;
  auth: VisualRouteAuth;
  category: VisualRouteCategory;
  description: string;
};

export const VISUAL_AUDIT_ROUTES: VisualAuditRoute[] = [
  {
    slug: 'home',
    path: '/',
    auth: 'public',
    category: 'public',
    description: 'Root public landing experience.',
  },
  {
    slug: 'landing',
    path: '/landing',
    auth: 'public',
    category: 'public',
    description: 'Dedicated marketing landing page.',
  },
  {
    slug: 'pricing',
    path: '/pricing',
    auth: 'public',
    category: 'public',
    description: 'Public pricing page.',
  },
  {
    slug: 'the-app',
    path: '/the-app',
    auth: 'public',
    category: 'public',
    description: 'Public app overview page.',
  },
  {
    slug: 'method',
    path: '/method',
    auth: 'public',
    category: 'public',
    description: 'Public method page.',
  },
  {
    slug: 'labs-marketing',
    path: '/labs',
    auth: 'public',
    category: 'public',
    description: 'Public labs marketing page.',
  },
  {
    slug: 'download-app',
    path: '/download-app',
    auth: 'public',
    category: 'public',
    description: 'Public mobile app download page.',
  },
  {
    slug: 'welcome',
    path: '/welcome',
    auth: 'public',
    category: 'public',
    description: 'Welcome entry screen.',
  },
  {
    slug: 'welcome-manifesto',
    path: '/welcome/manifesto',
    auth: 'public',
    category: 'public',
    description: 'Welcome manifesto screen.',
  },
  {
    slug: 'auth-login',
    path: '/auth/login',
    auth: 'public',
    category: 'public',
    description: 'Primary sign-in screen.',
  },
  {
    slug: 'auth-signup',
    path: '/auth/signup',
    auth: 'public',
    category: 'public',
    description: 'Primary sign-up screen.',
  },
  {
    slug: 'auth-forgot',
    path: '/auth/forgot',
    auth: 'public',
    category: 'public',
    description: 'Forgot-password screen.',
  },
  {
    slug: 'terms',
    path: '/terms',
    auth: 'public',
    category: 'public',
    description: 'Public terms page.',
  },
  {
    slug: 'privacy',
    path: '/privacy',
    auth: 'public',
    category: 'public',
    description: 'Public privacy page.',
  },
  {
    slug: 'app-today',
    path: '/app/today',
    auth: 'user',
    category: 'authenticated',
    description: 'Primary authenticated Today screen.',
  },
  {
    slug: 'app-workouts',
    path: '/app/workouts',
    auth: 'user',
    category: 'authenticated',
    description: 'Primary workouts hub.',
  },
  {
    slug: 'app-workout-history',
    path: '/app/workouts/history',
    auth: 'user',
    category: 'authenticated',
    description: 'Workout history screen.',
  },
  {
    slug: 'app-routine-presets',
    path: '/app/routines/presets',
    auth: 'user',
    category: 'authenticated',
    description: 'Routine preset library.',
  },
  {
    slug: 'app-nutrition',
    path: '/app/nutrition',
    auth: 'user',
    category: 'authenticated',
    description: 'Primary nutrition hub.',
  },
  {
    slug: 'app-nutrition-diary',
    path: '/app/nutrition/diary',
    auth: 'user',
    category: 'authenticated',
    description: 'Food diary screen.',
  },
  {
    slug: 'app-nutrition-targets',
    path: '/app/nutrition/targets',
    auth: 'user',
    category: 'authenticated',
    description: 'Macro targets screen.',
  },
  {
    slug: 'app-body',
    path: '/app/body',
    auth: 'user',
    category: 'authenticated',
    description: 'Body dashboard.',
  },
  {
    slug: 'app-body-photos',
    path: '/app/body/progress/photos',
    auth: 'user',
    category: 'authenticated',
    description: 'Progress photos library.',
  },
  {
    slug: 'app-labs',
    path: '/app/labs',
    auth: 'user',
    category: 'authenticated',
    description: 'Labs hub.',
  },
  {
    slug: 'app-coach',
    path: '/app/coach',
    auth: 'user',
    category: 'authenticated',
    description: 'Coach home.',
  },
  {
    slug: 'app-social',
    path: '/app/social',
    auth: 'user',
    category: 'authenticated',
    description: 'Social feed.',
  },
  {
    slug: 'app-profile',
    path: '/app/profile',
    auth: 'user',
    category: 'authenticated',
    description: 'Profile hub.',
  },
  {
    slug: 'app-settings',
    path: '/app/settings',
    auth: 'user',
    category: 'authenticated',
    description: 'App settings screen.',
  },
  {
    slug: 'webapp-account',
    path: '/webapp/account',
    auth: 'user',
    category: 'authenticated',
    description: 'Web account hub.',
  },
  {
    slug: 'webapp-billing-manage',
    path: '/webapp/billing/manage',
    auth: 'user',
    category: 'authenticated',
    description: 'Web billing management page.',
  },
  {
    slug: 'webapp-settings',
    path: '/webapp/settings',
    auth: 'user',
    category: 'authenticated',
    description: 'Web account settings page.',
  },
  {
    slug: 'app-protocols',
    path: '/app/protocols',
    auth: 'user',
    category: 'hidden-internal',
    description: 'Hidden internal protocols home.',
  },
  {
    slug: 'app-protocols-empty',
    path: '/app/protocols/empty',
    auth: 'user',
    category: 'hidden-internal',
    description: 'Hidden empty-state protocol page.',
  },
  {
    slug: 'app-protocols-new',
    path: '/app/protocols/new',
    auth: 'user',
    category: 'hidden-internal',
    description: 'Hidden internal protocol creation page.',
  },
  {
    slug: 'app-paywall',
    path: '/app/paywall',
    auth: 'user',
    category: 'hidden-internal',
    description: 'Hidden internal mobile paywall page.',
  },
  {
    slug: 'app-pr-moment',
    path: '/app/pr-moment',
    auth: 'user',
    category: 'hidden-internal',
    description: 'Hidden internal celebration/PR page.',
  },
  {
    slug: 'app-empty-states',
    path: '/app/empty-states',
    auth: 'user',
    category: 'hidden-internal',
    description: 'Hidden internal empty-states showcase.',
  },
  {
    slug: 'app-errors',
    path: '/app/errors',
    auth: 'user',
    category: 'hidden-internal',
    description: 'Hidden internal error showcase.',
  },
  {
    slug: 'webapp-settings-danger',
    path: '/webapp/settings/danger',
    auth: 'user',
    category: 'hidden-internal',
    description: 'Danger zone route.',
  },
  {
    slug: 'webapp-settings-diagnostics',
    path: '/webapp/settings/diagnostics',
    auth: 'user',
    category: 'hidden-internal',
    description: 'Diagnostics route.',
  },
  {
    slug: 'maintenance',
    path: '/maintenance',
    auth: 'public',
    category: 'hidden-internal',
    description: 'Maintenance state page.',
  },
  {
    slug: 'force-update',
    path: '/force-update',
    auth: 'public',
    category: 'hidden-internal',
    description: 'Force-update page.',
  },
  {
    slug: 'server-error',
    path: '/500',
    auth: 'public',
    category: 'hidden-internal',
    description: '500 page.',
  },
  {
    slug: 'not-found',
    path: '/404',
    auth: 'public',
    category: 'hidden-internal',
    description: '404 page.',
  },
];

export const MANUAL_VISUAL_REVIEW_AREAS = [
  {
    area: 'Parameterized routes that require seeded IDs',
    routes: [
      '/app/workouts/:id',
      '/app/routines/:id',
      '/app/routines/presets/:id',
      '/app/labs/biomarker/:id',
      '/app/labs/exam/:id',
      '/app/coach/insights/:id',
      '/app/protocols/:id',
      '/app/u/:username',
      '/app/exercises/:id',
      '/app/nutrition/food/:id',
      '/app/nutrition/meal/:id',
      '/app/today/celebrate/:kind',
    ],
    reason: 'These need stable fixture data before screenshots are trustworthy.',
  },
  {
    area: 'Native or hardware-driven flows',
    routes: [
      '/app/nutrition/capture',
      '/app/nutrition/photo',
      '/app/nutrition/photo/confirm',
      '/app/nutrition/voice',
      '/app/body/progress/photos/capture',
      '/app/watch',
    ],
    reason: 'Camera, microphone, native permissions, and device-specific surfaces need manual or native-targeted validation.',
  },
  {
    area: 'Stateful workflow routes',
    routes: [
      '/auth/callback',
      '/auth/magic',
      '/auth/reset',
      '/onboarding',
      '/onboarding/goal',
      '/onboarding/activity',
      '/onboarding/stats',
      '/onboarding/diet',
      '/onboarding/workout',
      '/onboarding/habits',
      '/onboarding/constraints',
      '/onboarding/summary',
      '/onboarding/paywall',
      '/onboarding/tour',
      '/onboarding/smart',
    ],
    reason: 'These depend on auth tokens, URL payloads, or multistep in-progress state and need scenario-specific baselines.',
  },
  {
    area: 'Action-heavy hidden routes',
    routes: [
      '/app/workouts/active',
      '/app/workouts/manual-plan',
      '/app/social/share',
      '/app/export',
      '/webapp/export',
    ],
    reason: 'These pages render, but design validation is better after stable seeded data and richer interaction-state coverage.',
  },
];
