/**
 * Atlas.Core — Onboarding Schema
 * 28-screen flow. i18n keys reference onboardingV2.* translations.
 * Each screen keeps the original English string as a fallback so the
 * flow works even when translations are missing.
 */

const screens = [
  // ─── ACT 1 — HOOK ──────────────────────────────────────────────
  {
    id: 'splash',
    act: 1,
    type: 'splash',
    autoAdvanceMs: 2500,
  },
  {
    id: 'welcome-hook',
    act: 1,
    type: 'hook',
    titleKey: 'onboardingV2.hook.title',
    title: 'The scale lies. Your mirror lies. Your last app had no idea what was working.',
    subtitleKey: 'onboardingV2.hook.subtitle',
    subtitle:
      'Atlas tracks what actually matters — and adjusts every week so you stop guessing.',
    ctaKey: 'onboardingV2.hook.cta',
    cta: 'Show me how',
    secondaryCtaKey: 'onboardingV2.hook.secondary',
    secondaryCta: 'I already have an account',
  },

  // ─── ACT 2 — QUIZ ──────────────────────────────────────────────
  {
    id: 'q-primary-goal',
    act: 2,
    type: 'multi-select',
    fieldKey: 'health_goals',
    titleKey: 'onboardingV2.quiz.primaryGoal.title',
    title: 'What are you actually trying to do?',
    subtitleKey: 'onboardingV2.quiz.primaryGoal.subtitle',
    subtitle: 'Pick everything that applies. We build around all of them.',
    options: [
      { value: 'fat_loss', emoji: '🔥', labelKey: 'onboardingV2.quiz.primaryGoal_fat_loss', label: 'Lose fat' },
      { value: 'muscle_gain', emoji: '💪', labelKey: 'onboardingV2.quiz.primaryGoal_muscle_gain', label: 'Build muscle' },
      { value: 'recomp', emoji: '🔄', labelKey: 'onboardingV2.quiz.primaryGoal_recomp', label: 'Recomp — lose fat & gain muscle' },
      { value: 'energy_health', emoji: '⚡', labelKey: 'onboardingV2.quiz.primaryGoal_energy_health', label: 'More energy & better health markers' },
      { value: 'event_prep', emoji: '🎯', labelKey: 'onboardingV2.quiz.primaryGoal_event_prep', label: 'Prep for a specific event or date' },
    ],
    minSelections: 1,
    maxSelections: 3,
    showInProgress: true,
  },
  {
    id: 'q-target-weight',
    act: 2,
    type: 'numeric-input',
    fieldKey: 'target_weight',
    titleKey: 'onboardingV2.quiz.targetWeight.title',
    title: 'What weight do you want to hit?',
    subtitleKey: 'onboardingV2.quiz.targetWeight.subtitle',
    subtitle:
      "Rough number is fine. We'll refine this once we see your body composition data.",
    placeholder: '75',
    min: 30,
    max: 250,
    unit: 'kg',
    showInProgress: true,
  },
  {
    id: 'q-timeline',
    act: 2,
    type: 'single-select',
    fieldKey: 'timeline',
    titleKey: 'onboardingV2.quiz.timeline.title',
    title: 'When do you want to get there?',
    subtitleKey: 'onboardingV2.quiz.timeline.subtitle',
    subtitle: "We'll tell you if this is realistic — no sugarcoating.",
    options: [
      { value: '6w', emoji: '⚡', labelKey: 'onboardingV2.quiz.timeline_6w', label: '6 weeks — aggressive but doable' },
      { value: '3m', emoji: '📅', labelKey: 'onboardingV2.quiz.timeline_3m', label: '3 months — the sweet spot for most people' },
      { value: '6m', emoji: '🏔️', labelKey: 'onboardingV2.quiz.timeline_6m', label: '6 months — sustainable pace, big transformation' },
      { value: 'specific_date', emoji: '🎯', labelKey: 'onboardingV2.quiz.timeline_specific_date', label: 'I have a specific date' },
    ],
    autoAdvance: true,
    showInProgress: true,
  },
  {
    id: 'q-body-stats',
    act: 2,
    type: 'body-stats',
    fieldKeys: ['sex', 'age', 'height_cm', 'current_weight'],
    titleKey: 'onboardingV2.quiz.bodyStats.title',
    title: 'The basics',
    subtitleKey: 'onboardingV2.quiz.bodyStats.subtitle',
    subtitle:
      'We use these to calculate your metabolism. Nothing leaves your device without your permission.',
    showInProgress: true,
  },
  {
    id: 'q-activity-baseline',
    act: 2,
    type: 'single-select',
    fieldKey: 'activity_level',
    titleKey: 'onboardingV2.quiz.activityBaseline.title',
    title: 'How active are you outside of training?',
    subtitleKey: 'onboardingV2.quiz.activityBaseline.subtitle',
    subtitle: 'Think about a typical weekday — not your best week.',
    options: [
      { value: 'barely', emoji: '🪑', labelKey: 'onboardingV2.quiz.activityBaseline_barely', label: 'Desk job, barely move' },
      { value: 'light', emoji: '🚶', labelKey: 'onboardingV2.quiz.activityBaseline_light', label: 'Some walking, mostly sedentary' },
      { value: 'moderate', emoji: '🏃', labelKey: 'onboardingV2.quiz.activityBaseline_moderate', label: 'On my feet a fair amount' },
      { value: 'high', emoji: '🔨', labelKey: 'onboardingV2.quiz.activityBaseline_high', label: 'Physical job or very active lifestyle' },
      { value: 'athlete', emoji: '🏋️', labelKey: 'onboardingV2.quiz.activityBaseline_athlete', label: 'Training 5+ times a week already' },
    ],
    autoAdvance: true,
    showInProgress: true,
  },

  // ─── INTERSTITIAL 1 ────────────────────────────────────────────
  {
    id: 'interstitial-social',
    act: 2,
    type: 'interstitial',
    titleKey: 'onboardingV2.interstitial.social.title',
    title: "You're in good company.",
    subtitleKey: 'onboardingV2.interstitial.social.subtitle',
    subtitle:
      'Over 12,000 people have used Atlas to hit a goal they actually cared about.',
    emoji: '🤝',
  },

  {
    id: 'q-past-attempts',
    act: 2,
    type: 'multi-select',
    fieldKey: 'past_attempts',
    titleKey: 'onboardingV2.quiz.pastAttempts.title',
    title: "What have you already tried that didn't stick?",
    subtitleKey: 'onboardingV2.quiz.pastAttempts.subtitle',
    subtitle: 'No judgment. We just need to know what to do differently.',
    options: [
      { value: 'calorie_tracker', emoji: '📱', labelKey: 'onboardingV2.quiz.pastAttempts_calorie_tracker', label: 'Calorie tracking app' },
      { value: 'strict_diet', emoji: '🥗', labelKey: 'onboardingV2.quiz.pastAttempts_strict_diet', label: 'Strict diet or meal plan' },
      { value: 'personal_trainer', emoji: '🏋️', labelKey: 'onboardingV2.quiz.pastAttempts_personal_trainer', label: 'Personal trainer' },
      { value: 'fitness_app', emoji: '📲', labelKey: 'onboardingV2.quiz.pastAttempts_fitness_app', label: 'Another fitness app' },
      { value: 'eating_clean', emoji: '🥑', labelKey: 'onboardingV2.quiz.pastAttempts_eating_clean', label: '"Eating clean" without tracking' },
      { value: 'first_attempt', emoji: '🆕', labelKey: 'onboardingV2.quiz.pastAttempts_first_attempt', label: "This is my first real attempt" },
    ],
    minSelections: 1,
    maxSelections: 6,
    showInProgress: true,
  },
  {
    id: 'q-biggest-blocker',
    act: 2,
    type: 'single-select',
    fieldKey: 'biggest_blocker',
    titleKey: 'onboardingV2.quiz.biggestBlocker.title',
    title: 'What usually kills your momentum?',
    subtitleKey: 'onboardingV2.quiz.biggestBlocker.subtitle',
    subtitle: 'Pick the one that hits hardest.',
    options: [
      { value: 'no_time', emoji: '⏰', labelKey: 'onboardingV2.quiz.biggestBlocker_no_time', label: "I don't have time to track everything" },
      { value: 'lose_motivation', emoji: '📉', labelKey: 'onboardingV2.quiz.biggestBlocker_lose_motivation', label: 'I lose motivation after 2–3 weeks' },
      { value: 'weekends', emoji: '🍕', labelKey: 'onboardingV2.quiz.biggestBlocker_weekends', label: 'Weekends destroy my progress' },
      { value: 'dont_know_working', emoji: '❓', labelKey: 'onboardingV2.quiz.biggestBlocker_dont_know_working', label: "I never know if what I'm doing is working" },
      { value: 'chaotic_schedule', emoji: '🌀', labelKey: 'onboardingV2.quiz.biggestBlocker_chaotic_schedule', label: 'My schedule is too chaotic' },
      { value: 'plateau', emoji: '📊', labelKey: 'onboardingV2.quiz.biggestBlocker_plateau', label: 'I hit a plateau and quit' },
    ],
    autoAdvance: true,
    showInProgress: true,
  },
  {
    id: 'q-eating-patterns',
    act: 2,
    type: 'single-select',
    fieldKey: 'eating_pattern',
    titleKey: 'onboardingV2.quiz.eatingPatterns.title',
    title: 'How do you actually eat on a normal day?',
    subtitleKey: 'onboardingV2.quiz.eatingPatterns.subtitle',
    subtitle: "Be honest — we're building around your life, not a textbook.",
    options: [
      { value: 'three_meals', emoji: '🍽️', labelKey: 'onboardingV2.quiz.eatingPatterns_three_meals', label: '3 meals, pretty consistent' },
      { value: 'skipper', emoji: '⏭️', labelKey: 'onboardingV2.quiz.eatingPatterns_skipper', label: 'I skip meals — usually breakfast' },
      { value: 'grazer', emoji: '🍿', labelKey: 'onboardingV2.quiz.eatingPatterns_grazer', label: 'I graze all day, no real structure' },
      { value: 'evening_eater', emoji: '🌙', labelKey: 'onboardingV2.quiz.eatingPatterns_evening_eater', label: 'Small during the day, big at night' },
      { value: 'chaotic', emoji: '🎲', labelKey: 'onboardingV2.quiz.eatingPatterns_chaotic', label: 'Completely different every day' },
    ],
    autoAdvance: true,
    showInProgress: true,
  },
  {
    id: 'q-training-prefs',
    act: 2,
    type: 'single-select',
    fieldKey: 'training_environment',
    titleKey: 'onboardingV2.quiz.trainingPrefs.title',
    title: 'Where do you train?',
    subtitleKey: 'onboardingV2.quiz.trainingPrefs.subtitle',
    subtitle: 'This determines your exercise library.',
    options: [
      { value: 'full_gym', emoji: '🏢', labelKey: 'onboardingV2.quiz.trainingPrefs_full_gym', label: 'Full gym with everything' },
      { value: 'home_barbell', emoji: '🏠', labelKey: 'onboardingV2.quiz.trainingPrefs_home_barbell', label: 'Home gym — barbell & rack' },
      { value: 'home_dumbbells', emoji: '🏠', labelKey: 'onboardingV2.quiz.trainingPrefs_home_dumbbells', label: 'Home — dumbbells only' },
      { value: 'bodyweight', emoji: '🤸', labelKey: 'onboardingV2.quiz.trainingPrefs_bodyweight', label: 'Bodyweight only' },
      { value: 'no_training', emoji: '🚫', labelKey: 'onboardingV2.quiz.trainingPrefs_no_training', label: "I'm not training right now" },
    ],
    autoAdvance: true,
    showInProgress: true,
  },

  // ─── INTERSTITIAL 2 ────────────────────────────────────────────
  {
    id: 'interstitial-stats',
    act: 2,
    type: 'interstitial',
    titleKey: 'onboardingV2.interstitial.stats.title',
    title: 'Over 12,000 people have built their plan here.',
    subtitleKey: 'onboardingV2.interstitial.stats.subtitle',
    subtitle: 'The average Atlas user sees measurable change in 11 days.',
    emoji: '📈',
  },

  {
    id: 'q-current-body',
    act: 2,
    type: 'body-select',
    fieldKey: 'current_body_type',
    titleKey: 'onboardingV2.quiz.currentBody.title',
    title: 'Which describes your body today?',
    subtitleKey: 'onboardingV2.quiz.currentBody.subtitle',
    subtitle: "Tap the closest match. This helps us set realistic milestones.",
    showInProgress: true,
  },
  {
    id: 'q-desired-body',
    act: 2,
    type: 'body-select',
    fieldKey: 'desired_body_type',
    titleKey: 'onboardingV2.quiz.desiredBody.title',
    title: 'Which describes where you want to be?',
    subtitleKey: 'onboardingV2.quiz.desiredBody.subtitle',
    subtitle: "Pick your target. We'll shape your plan around getting there.",
    showInProgress: true,
  },
  {
    id: 'q-what-would-change',
    act: 2,
    type: 'multi-select',
    fieldKey: 'desired_outcomes',
    titleKey: 'onboardingV2.quiz.whatWouldChange.title',
    title: 'If you actually hit this goal — what changes?',
    subtitleKey: 'onboardingV2.quiz.whatWouldChange.subtitle',
    subtitle: "Pick what matters to you. We'll come back to these.",
    options: [
      { value: 'clothes_fit', emoji: '👕', labelKey: 'onboardingV2.quiz.whatWouldChange_clothes_fit', label: 'My clothes fit the way I want' },
      { value: 'more_energy', emoji: '⚡', labelKey: 'onboardingV2.quiz.whatWouldChange_more_energy', label: 'I have energy through the whole day' },
      { value: 'confidence', emoji: '🪞', labelKey: 'onboardingV2.quiz.whatWouldChange_confidence', label: "I'm not avoiding mirrors anymore" },
      { value: 'better_labs', emoji: '🩸', labelKey: 'onboardingV2.quiz.whatWouldChange_better_labs', label: 'My bloodwork and health markers improve' },
      { value: 'stronger_lifts', emoji: '🏋️', labelKey: 'onboardingV2.quiz.whatWouldChange_stronger_lifts', label: "I'm actually strong, not just lean" },
      { value: 'feel_like_myself', emoji: '🧠', labelKey: 'onboardingV2.quiz.whatWouldChange_feel_like_myself', label: 'I feel like myself again' },
    ],
    minSelections: 1,
    maxSelections: 6,
    showInProgress: true,
  },
  {
    id: 'q-tracking-history',
    act: 2,
    type: 'single-select',
    fieldKey: 'tracking_experience',
    titleKey: 'onboardingV2.quiz.trackingHistory.title',
    title: 'Have you tracked calories or macros before?',
    subtitleKey: 'onboardingV2.quiz.trackingHistory.subtitle',
    subtitle: 'This changes how we onboard you into the tracker.',
    options: [
      { value: 'a_lot', emoji: '📊', labelKey: 'onboardingV2.quiz.trackingHistory_a_lot', label: "Yes — I've done it seriously" },
      { value: 'some', emoji: '📝', labelKey: 'onboardingV2.quiz.trackingHistory_some', label: 'A bit, but never consistently' },
      { value: 'none', emoji: '🆕', labelKey: 'onboardingV2.quiz.trackingHistory_none', label: 'Never' },
    ],
    autoAdvance: true,
    showInProgress: true,
  },
  {
    id: 'q-connected-apps',
    act: 2,
    type: 'connected-apps',
    titleKey: 'onboardingV2.quiz.connectedApps.title',
    title: 'Connect your health data',
    subtitleKey: 'onboardingV2.quiz.connectedApps.subtitle',
    subtitle: 'We pull in your data so you start with context, not a blank slate.',
    showInProgress: true,
  },
  {
    id: 'q-notifications',
    act: 2,
    type: 'notifications',
    titleKey: 'onboardingV2.quiz.notifications.title',
    title: 'Want a nudge when it matters?',
    subtitleKey: 'onboardingV2.quiz.notifications.subtitle',
    subtitle:
      'One check-in in the morning, one at night. No spam. You can turn these off anytime.',
    showInProgress: true,
  },

  // ─── ACT 3 — CONVERSION ────────────────────────────────────────
  {
    id: 'interstitial-building',
    act: 3,
    type: 'interstitial',
    titleKey: 'onboardingV2.interstitial.building.title',
    title: 'Building your plan...',
    subtitleKey: 'onboardingV2.interstitial.building.subtitle',
    subtitle: 'Crunching your numbers against 12,000+ real results.',
    emoji: '⚙️',
  },
  {
    id: 'building',
    act: 3,
    type: 'building',
    messageKeys: [
      'onboardingV2.building.msg1',
      'onboardingV2.building.msg2',
      'onboardingV2.building.msg3',
      'onboardingV2.building.msg4',
      'onboardingV2.building.msg5',
      'onboardingV2.building.msg6',
    ],
    messages: [
      'Analyzing your metabolism...',
      'Comparing against similar profiles...',
      'Calculating your optimal deficit...',
      'Mapping your training split...',
      'Setting weekly milestones...',
      'Generating your first week...',
    ],
    autoAdvanceMs: 3500,
  },
  {
    id: 'analysis',
    act: 3,
    type: 'projection',
    titleKey: 'onboardingV2.projection.title',
    title: 'Here\'s what we found',
  },
  {
    id: 'projection',
    act: 3,
    type: 'projection',
    titleKey: 'onboardingV2.projection.weightTitle',
    title: 'Your weight projection',
  },
  {
    id: 'social-proof',
    act: 3,
    type: 'social-proof',
    titleKey: 'onboardingV2.socialProof.title',
    title: 'People like you are getting results',
    testimonials: [
      {
        name: 'Marco',
        age: 31,
        goalKey: 'onboardingV2.socialProof.testimonials.marco.goal',
        goal: 'Fat loss',
        quoteKey: 'onboardingV2.socialProof.testimonials.marco.quote',
        quote:
          'I lost 9 kg in 10 weeks. The weekly adjustments meant I never stalled — first time that\'s happened.',
        metricKey: 'onboardingV2.socialProof.testimonials.marco.metric',
        metric: '-9 kg in 10 weeks',
      },
      {
        name: 'Sarah',
        age: 27,
        goalKey: 'onboardingV2.socialProof.testimonials.sarah.goal',
        goal: 'Recomp',
        quoteKey: 'onboardingV2.socialProof.testimonials.sarah.quote',
        quote:
          'I\'ve used every app. Atlas is the only one that changed what I was doing based on what was actually happening.',
        metricKey: 'onboardingV2.socialProof.testimonials.sarah.metric',
        metric: '-6 kg fat, +2 kg muscle',
      },
      {
        name: 'James',
        age: 44,
        goalKey: 'onboardingV2.socialProof.testimonials.james.goal',
        goal: 'Energy & health',
        quoteKey: 'onboardingV2.socialProof.testimonials.james.quote',
        quote:
          'My bloodwork improved in 8 weeks. My doctor asked what I changed. I just said "I stopped guessing."',
        metricKey: 'onboardingV2.socialProof.testimonials.james.metric',
        metric: 'Bloodwork normalized in 8 weeks',
      },
    ],
  },
  {
    id: 'commitment',
    act: 3,
    type: 'commitment',
    titleKey: 'onboardingV2.commitment.title',
    title: 'One commitment before we start',
    bodyKey: 'onboardingV2.commitment.body',
    body:
      "You don't need to be perfect. You need to be consistent enough that Atlas can learn what works for you. Log honestly. Check in weekly. Trust the adjustments. That's it.",
    primaryCtaKey: 'onboardingV2.commitment.primaryCta',
    primaryCta: "I'm in — let's go",
    secondaryCtaKey: 'onboardingV2.commitment.secondaryCta',
    secondaryCta: 'I need to think about it',
  },
  {
    id: 'trial-explainer',
    act: 3,
    type: 'trial-explainer',
    titleKey: 'onboardingV2.trial.title',
    title: 'How your free trial works',
    steps: [
      {
        labelKey: 'onboardingV2.trial.today',
        label: 'Today — full access, zero charge',
        detailKey: 'onboardingV2.trial.todayText',
        detail:
          'Your plan is built. Start logging, get your first weekly review, and see the system work.',
      },
      {
        labelKey: 'onboardingV2.trial.day5',
        label: 'Day 5 — we remind you',
        detailKey: 'onboardingV2.trial.day5Text',
        detail:
          "You'll get a heads up before anything is charged. No tricks.",
      },
      {
        labelKey: 'onboardingV2.trial.day7',
        label: 'Day 7 — trial ends',
        detailKey: 'onboardingV2.trial.day7Text',
        detail:
          "If Atlas isn't worth it, cancel in one tap. If it is, your subscription starts automatically.",
      },
    ],
  },
  {
    id: 'paywall',
    act: 3,
    type: 'paywall',
  },
  {
    id: 'account-creation',
    act: 3,
    type: 'account-creation',
    titleKey: 'onboardingV2.account.title',
    title: 'Create your account',
    subtitleKey: 'onboardingV2.account.subtitle',
    subtitle:
      "Your plan is ready. Sign up so we can save your progress and start your first week.",
  },
];

/**
 * Count of quiz / progress-tracked screens (those with showInProgress: true).
 * Used by the progress bar component.
 */
export const QUIZ_SCREEN_COUNT = screens.filter((s) => s.showInProgress).length;

export const ONBOARDING_SCHEMA = screens;

export default screens;
