/**
 * send-beta-invite — Create a beta invite record and send the invite email
 *
 * Auth: Service-role JWT (admin only — called from the admin panel)
 *
 * Body: { email: string, firstName?: string, notes?: string }
 *
 * Deploy:
 *   supabase functions deploy send-beta-invite
 */

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { sendBetaInvite } from '../_shared/email-service.ts';

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: CORS });
  }

  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), {
      status: 405,
      headers: { ...CORS, 'Content-Type': 'application/json' },
    });
  }

  // Verify the caller is an admin via their JWT
  const authHeader = req.headers.get('authorization');
  if (!authHeader) {
    return new Response(JSON.stringify({ error: 'Missing authorization header' }), {
      status: 401,
      headers: { ...CORS, 'Content-Type': 'application/json' },
    });
  }

  const supabaseAdmin = createClient(
    Deno.env.get('SUPABASE_URL') || '',
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') || ''
  );

  // Get the calling user from their JWT
  const supabaseUser = createClient(
    Deno.env.get('SUPABASE_URL') || '',
    Deno.env.get('SUPABASE_ANON_KEY') || '',
    { global: { headers: { Authorization: authHeader } } }
  );

  const { data: { user: caller }, error: authError } = await supabaseUser.auth.getUser();
  if (authError || !caller) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      status: 401,
      headers: { ...CORS, 'Content-Type': 'application/json' },
    });
  }

  // Verify the caller is an admin
  const { data: profile } = await supabaseAdmin
    .from('profiles')
    .select('role')
    .eq('id', caller.id)
    .single();

  if (profile?.role !== 'admin') {
    return new Response(JSON.stringify({ error: 'Forbidden' }), {
      status: 403,
      headers: { ...CORS, 'Content-Type': 'application/json' },
    });
  }

  let body: { email: string; firstName?: string; notes?: string };
  try {
    body = await req.json();
  } catch {
    return new Response(JSON.stringify({ error: 'Invalid JSON body' }), {
      status: 400,
      headers: { ...CORS, 'Content-Type': 'application/json' },
    });
  }

  const { email, firstName = '', notes = '' } = body;

  if (!email || typeof email !== 'string' || !email.includes('@')) {
    return new Response(JSON.stringify({ error: 'Valid email is required' }), {
      status: 400,
      headers: { ...CORS, 'Content-Type': 'application/json' },
    });
  }

  // Check for existing pending invite to this email
  const { data: existing } = await supabaseAdmin
    .from('beta_invites')
    .select('id, status')
    .eq('email', email.toLowerCase().trim())
    .eq('status', 'pending')
    .maybeSingle();

  if (existing) {
    return new Response(JSON.stringify({ error: 'A pending invite already exists for this email' }), {
      status: 409,
      headers: { ...CORS, 'Content-Type': 'application/json' },
    });
  }

  // Create invite record (token is auto-generated by DB default)
  const { data: invite, error: insertError } = await supabaseAdmin
    .from('beta_invites')
    .insert({
      email: email.toLowerCase().trim(),
      invited_by: caller.id,
      notes: notes || null,
    })
    .select()
    .single();

  if (insertError || !invite) {
    console.error('send-beta-invite: Failed to create invite:', insertError);
    return new Response(JSON.stringify({ error: 'Failed to create invite' }), {
      status: 500,
      headers: { ...CORS, 'Content-Type': 'application/json' },
    });
  }

  const appUrl = Deno.env.get('APP_URL') || 'https://atlascore.app';
  const inviteUrl = `${appUrl}/invite?token=${invite.token}`;

  // Send invite email
  const emailResult = await sendBetaInvite(
    invite.email,
    firstName,
    inviteUrl,
    notes || undefined
  );

  if (!emailResult.success) {
    console.error('send-beta-invite: Email send failed:', emailResult.error);
    // Don't fail the request — invite record exists, can retry email later
  }

  console.log(`send-beta-invite: Invite created id=${invite.id} email=${invite.email} emailSent=${emailResult.success}`);

  return new Response(JSON.stringify({
    id: invite.id,
    email: invite.email,
    token: invite.token,
    inviteUrl,
    expiresAt: invite.expires_at,
    emailSent: emailResult.success,
  }), {
    status: 200,
    headers: { ...CORS, 'Content-Type': 'application/json' },
  });
});
