import React from 'react';
import V3MarketingLayout, { MC } from './V3MarketingLayout.jsx';
import { ACBrand, ACFonts } from '@/redesign/v3/lib/paper.jsx';

const LAST_UPDATED = 'April 2026';

function Section({ n, title, children }) {
  return (
    <section>
      <h2 style={{
        fontSize: 20, fontWeight: 700, letterSpacing: -0.3, lineHeight: 1.2,
        margin: '0 0 12px', color: MC.fg,
      }}>
        <span style={{ fontVariantNumeric: 'tabular-nums', color: MC.mute, marginRight: 10, fontWeight: 600 }}>
          {n}.
        </span>
        {title}
      </h2>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        {children}
      </div>
    </section>
  );
}

function P({ children }) {
  return (
    <p style={{ margin: 0, fontSize: 14.5, color: MC.body, lineHeight: 1.7 }}>
      {children}
    </p>
  );
}

function List({ items }) {
  return (
    <ul style={{ margin: 0, paddingLeft: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 10 }}>
      {items.map((item, i) => (
        <li key={i} style={{ paddingLeft: 18, position: 'relative', fontSize: 14.5, color: MC.body, lineHeight: 1.65 }}>
          <span aria-hidden style={{ position: 'absolute', left: 0, top: 11, width: 6, height: 6, borderRadius: 9999, background: MC.accent }} />
          {item}
        </li>
      ))}
    </ul>
  );
}

export default function V3Privacy() {
  return (
    <V3MarketingLayout
      eyebrow="/// legal"
      title={<>privacy <span style={{ color: MC.accent }}>policy.</span></>}
      intro={`Last updated: ${LAST_UPDATED}`}
      hideCTAs
    >
      <div style={{ display: 'flex', flexDirection: 'column', gap: 32, maxWidth: 820 }}>

        <Section n="1" title="Our commitment">
          <P>
            atlas.core was built for people who take their bodies seriously, and we
            take your privacy seriously in return. This policy explains what data we
            collect, why we collect it, how we use it, and the rights you have over it.
          </P>
          <P>
            We do not sell your personal data. We do not share it with advertisers.
            We do not use it to train AI models for third parties.
          </P>
        </Section>

        <Section n="2" title="What we collect">
          <P>We collect information you provide directly and information generated by your use of the Service:</P>
          <List items={[
            'Account information: email address, name, and authentication credentials.',
            'Profile information: height, weight, date of birth, fitness goals, and training preferences.',
            'Activity data: workout logs, food entries, body measurements, progress photos, and lab results.',
            'Coach conversations: messages you exchange with the AI coach.',
            'Device information: device type, operating system, and app version for debugging and compatibility.',
            'Usage analytics: page views, feature usage patterns, and crash reports (anonymized where possible).',
          ]} />
        </Section>

        <Section n="3" title="How we use your data">
          <List items={[
            'To provide and operate the Service, including the AI coach, nutrition tracking, and workout logging.',
            'To personalize your experience: macro targets, training recommendations, and coach insights.',
            'To process payments and manage your subscription.',
            'To send transactional communications (password resets, billing receipts, critical security notices).',
            'To improve the Service through aggregated, anonymized analytics.',
            'To comply with legal obligations.',
          ]} />
        </Section>

        <Section n="4" title="Health data">
          <P>
            atlas.core handles health-adjacent data (body weight, body composition, food intake,
            lab results, progress photos). We treat all such data with elevated care:
          </P>
          <List items={[
            'Health data is encrypted in transit (TLS 1.3) and at rest (AES-256).',
            'Health data is never shared with third parties for advertising or marketing.',
            'Health data is never used to train AI models for third parties.',
            'You may export or delete your health data at any time from Settings.',
          ]} />
        </Section>

        <Section n="5" title="AI processing">
          <P>
            When you use the AI coach, your messages and relevant context (recent workouts,
            nutrition data, body metrics) are sent to third-party AI providers to generate
            responses. We use providers that do not retain or train on user data. Conversations
            are stored on our servers to provide chat history and continuity.
          </P>
        </Section>

        <Section n="6" title="Data sharing">
          <P>We share your data only in these limited circumstances:</P>
          <List items={[
            'Service providers: hosting (Supabase, Vercel), payment processing (Stripe, RevenueCat / App Store), analytics (Vercel Analytics), and AI inference providers — all under data processing agreements.',
            'Legal requirements: when required by law, subpoena, or court order.',
            'Business transfers: in connection with a merger, acquisition, or sale of assets (you will be notified).',
            'With your consent: social features (crew, shared workouts) share only what you explicitly choose to share.',
          ]} />
        </Section>

        <Section n="7" title="Data retention">
          <P>
            We retain your data for as long as your account is active. If you delete your
            account, we remove your personal data within 30 days. Anonymized, aggregated
            data may be retained indefinitely for analytics. Backup copies are purged
            within 90 days of account deletion.
          </P>
        </Section>

        <Section n="8" title="Your rights">
          <P>Depending on your jurisdiction, you may have the right to:</P>
          <List items={[
            'Access: request a copy of all personal data we hold about you.',
            'Rectification: correct inaccurate or incomplete data.',
            'Deletion: request deletion of your account and personal data.',
            'Portability: export your data in machine-readable formats (CSV, JSON).',
            'Restriction: limit how we process your data in certain circumstances.',
            'Objection: object to processing based on legitimate interests.',
          ]} />
          <P>
            To exercise any of these rights, go to Settings or email{' '}
            <a href="mailto:privacy@useatlascore.com" style={{ color: MC.accent }}>
              privacy@useatlascore.com
            </a>.
            We respond to all requests within 30 days.
          </P>
        </Section>

        <Section n="9" title="Cookies and tracking">
          <P>
            The atlas.core website uses minimal analytics (Vercel Analytics) and does not
            use third-party advertising cookies. The mobile app does not use cookies. We
            do not participate in cross-site tracking or retargeting networks.
          </P>
        </Section>

        <Section n="10" title="Children">
          <P>
            The Service is not directed at children under 18. We do not knowingly collect
            personal information from children. If you believe a child has provided us with
            personal data, contact us and we will delete it promptly.
          </P>
        </Section>

        <Section n="11" title="International transfers">
          <P>
            Your data may be processed in countries other than your own (including the
            United States and Brazil). We ensure appropriate safeguards are in place,
            including standard contractual clauses where required by GDPR or LGPD.
          </P>
        </Section>

        <Section n="12" title="Changes to this policy">
          <P>
            We may update this policy from time to time. Material changes will be
            communicated through the Service or via email. Your continued use after
            a change becomes effective constitutes acceptance.
          </P>
        </Section>

        <Section n="13" title="Contact">
          <P>
            Questions about this policy? Email us at{' '}
            <a href="mailto:privacy@useatlascore.com" style={{ color: MC.accent }}>
              privacy@useatlascore.com
            </a>.
          </P>
        </Section>

      </div>
    </V3MarketingLayout>
  );
}
