/**
 * Screen Registry for Atlas Core Redesign
 * 
 * Canonical source of truth for all screens in the application.
 * This registry is used to generate route configurations, RBAC checks, 
 * and breadcrumb systems.
 */

export type ScreenAccess = 'public' | 'free' | 'premium';
export type UserRole = 'athlete' | 'coach' | 'admin' | 'nutritionist' | 'clinician' | 'creator';
export type Platform = 'all' | 'web-only' | 'native-only';
export type LayoutType = 'app' | 'auth' | 'marketing' | 'admin' | 'none';

export interface ScreenEntry {
  id: string;
  path: string;
  domain: 'marketing' | 'auth' | 'onboarding' | 'dashboard' | 'training' | 'nutrition' | 'health' | 'insights' | 'profile' | 'social' | 'settings' | 'support' | 'admin' | 'professional' | 'misc';
  access: ScreenAccess;
  roles: UserRole[];
  platform: Platform;
  layout: LayoutType;
  redesignTarget?: string;
  legacyAliases?: string[];
  dependencies?: string[];
  states?: string[];
}

export interface OverlayEntry {
  id: string;
  domain: string;
  access: ScreenAccess;
}

const ALL_ROLES: UserRole[] = ['athlete', 'coach', 'admin', 'nutritionist', 'clinician', 'creator'];

export const SCREENS: ScreenEntry[] = [
  // --- Marketing Domain ---
  {
    id: 'landing',
    path: '/',
    domain: 'marketing',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
    legacyAliases: ['/Landing', '/home', '/landing'],
  },
  {
    id: 'pricing',
    path: '/Pricing',
    domain: 'marketing',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'blog',
    path: '/blog',
    domain: 'marketing',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'blog-post',
    path: '/blog/:slug',
    domain: 'marketing',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'help-center',
    path: '/help',
    domain: 'marketing',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'use-case',
    path: '/use-case/:role',
    domain: 'marketing',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },

  // --- Auth Domain ---
  {
    id: 'auth',
    path: '/auth',
    domain: 'auth',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'auth',
  },
  {
    id: 'login',
    path: '/login',
    domain: 'auth',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'auth',
  },
  {
    id: 'signup',
    path: '/signup',
    domain: 'auth',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'auth',
  },
  {
    id: 'auth-callback',
    path: '/auth/callback',
    domain: 'auth',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'update-password',
    path: '/auth/update-password',
    domain: 'auth',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'auth',
  },
  {
    id: 'invite-accept',
    path: '/invite',
    domain: 'auth',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'auth',
  },

  // --- Onboarding Domain ---
  {
    id: 'welcome',
    path: '/welcome',
    domain: 'onboarding',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'demo-home',
    path: '/preview',
    domain: 'onboarding',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
    legacyAliases: ['/demo'],
  },
  {
    id: 'onboarding',
    path: '/onboarding',
    domain: 'onboarding',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
    redesignTarget: 'OnboardingV2',
  },
  {
    id: 'smart-onboarding',
    path: '/onboarding-smart',
    domain: 'onboarding',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'splash',
    path: '/splash',
    domain: 'onboarding',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'native-only',
    layout: 'none',
  },

  // --- Dashboard Domain ---
  {
    id: 'today',
    path: '/Today',
    domain: 'dashboard',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
    redesignTarget: 'DashboardV2',
    legacyAliases: ['/today'],
  },

  // --- Training Domain ---
  {
    id: 'workouts',
    path: '/Workouts',
    domain: 'training',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
    redesignTarget: 'WorkoutsV2',
    legacyAliases: ['/workouts'],
  },
  {
    id: 'routines',
    path: '/Routines',
    domain: 'training',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'protocols',
    path: '/Protocols',
    domain: 'training',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'protocol-detail',
    path: '/Protocols/:id',
    domain: 'training',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'protocol-new',
    path: '/Protocols/new',
    domain: 'training',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'protocol-edit',
    path: '/Protocols/:id/edit',
    domain: 'training',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'exercises',
    path: '/Exercises',
    domain: 'training',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'exercise-detail',
    path: '/exercise/:id',
    domain: 'training',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'my-workout',
    path: '/my-workout',
    domain: 'training',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'manual-workout',
    path: '/manual-workout',
    domain: 'training',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'shared-workout',
    path: '/shared/workout/:token',
    domain: 'training',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },

  // --- Nutrition Domain ---
  {
    id: 'nutrition',
    path: '/Nutrition',
    domain: 'nutrition',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
    legacyAliases: ['/nutrition'],
  },
  {
    id: 'my-diet',
    path: '/my-diet',
    domain: 'nutrition',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'diary',
    path: '/diary',
    domain: 'nutrition',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'prescribed-diet',
    path: '/prescribed-diet',
    domain: 'nutrition',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },

  // --- Health Domain ---
  {
    id: 'measurements',
    path: '/Measurements',
    domain: 'health',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'lab-exams',
    path: '/LabExams',
    domain: 'health',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'body',
    path: '/body',
    domain: 'health',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'body-checkpoint-new',
    path: '/body/checkpoints/new',
    domain: 'health',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'none',
  },

  // --- Insights Domain ---
  {
    id: 'insights',
    path: '/Insights',
    domain: 'insights',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
    legacyAliases: ['/insights', '/AtlasAI', '/atlas-ai', '/ProgressReview'],
  },
  {
    id: 'block-review',
    path: '/block-review',
    domain: 'insights',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'progress',
    path: '/Progress',
    domain: 'insights',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
    redesignTarget: 'ProgressV2',
  },
  {
    id: 'progress-photos',
    path: '/progress-photos',
    domain: 'insights',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
    redesignTarget: 'ProgressPhotosV2',
  },
  {
    id: 'plan',
    path: '/Plan',
    domain: 'insights',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },

  // --- Profile Domain ---
  {
    id: 'profile',
    path: '/Profile',
    domain: 'profile',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'app',
    redesignTarget: 'ProfileV2',
  },
  {
    id: 'profile-edit',
    path: '/profile/edit',
    domain: 'profile',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'body-profile',
    path: '/body-profile',
    domain: 'profile',
    access: 'free',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'goals',
    path: '/goals',
    domain: 'profile',
    access: 'free',
    roles: ['athlete'],
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'account',
    path: '/account',
    domain: 'profile',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'user-content',
    path: '/profile/content',
    domain: 'profile',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'account-status',
    path: '/account-status',
    domain: 'profile',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'subscription',
    path: '/subscription',
    domain: 'profile',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'connected-services',
    path: '/connected-services',
    domain: 'profile',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'app',
  },

  // --- Social Domain ---
  {
    id: 'social',
    path: '/social',
    domain: 'social',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'feed',
    path: '/feed',
    domain: 'social',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'detail',
    path: '/detail/:id',
    domain: 'social',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'create-action',
    path: '/create',
    domain: 'social',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'creation-flow',
    path: '/create-new',
    domain: 'social',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'search',
    path: '/search',
    domain: 'social',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'saved-favorites',
    path: '/saved',
    domain: 'social',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'messages',
    path: '/messages',
    domain: 'social',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'streaks',
    path: '/streaks',
    domain: 'social',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'referral',
    path: '/referral',
    domain: 'social',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'achievements',
    path: '/achievements',
    domain: 'social',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'leaderboard',
    path: '/leaderboard',
    domain: 'social',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },

  // --- Settings Domain ---
  {
    id: 'settings',
    path: '/Settings',
    domain: 'settings',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'app',
    legacyAliases: ['/settings'],
  },
  {
    id: 'notifications',
    path: '/notifications',
    domain: 'settings',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'notification-settings',
    path: '/notification-settings',
    domain: 'settings',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'privacy-screen',
    path: '/settings/privacy',
    domain: 'settings',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'theme-screen',
    path: '/settings/theme',
    domain: 'settings',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'language-screen',
    path: '/settings/language',
    domain: 'settings',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'data-export',
    path: '/settings/export',
    domain: 'settings',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'app',
    legacyAliases: ['/Export'],
  },
  {
    id: 'delete-account',
    path: '/settings/delete-account',
    domain: 'settings',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'app',
  },

  // --- Support Domain ---
  {
    id: 'contact-support',
    path: '/support/contact',
    domain: 'support',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'terms-privacy',
    path: '/legal',
    domain: 'support',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'report-problem',
    path: '/report',
    domain: 'support',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'manage-consent',
    path: '/consent',
    domain: 'support',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'privacy-policy',
    path: '/privacy',
    domain: 'support',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'terms-of-service',
    path: '/terms',
    domain: 'support',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'tutorial',
    path: '/tutorial',
    domain: 'support',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'changelog',
    path: '/changelog',
    domain: 'support',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'rate-app',
    path: '/rate',
    domain: 'support',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'native-only',
    layout: 'none',
  },

  // --- Admin Domain ---
  {
    id: 'admin-overview',
    path: '/AdminPanel',
    domain: 'admin',
    access: 'free',
    roles: ['admin'],
    platform: 'web-only',
    layout: 'admin',
    legacyAliases: ['/admin'],
  },
  {
    id: 'admin-users',
    path: '/AdminPanel/users',
    domain: 'admin',
    access: 'free',
    roles: ['admin'],
    platform: 'web-only',
    layout: 'admin',
  },
  {
    id: 'admin-user-profile',
    path: '/AdminPanel/users/:userId',
    domain: 'admin',
    access: 'free',
    roles: ['admin'],
    platform: 'web-only',
    layout: 'admin',
  },
  {
    id: 'admin-ai-system',
    path: '/AdminPanel/ai-system',
    domain: 'admin',
    access: 'free',
    roles: ['admin'],
    platform: 'web-only',
    layout: 'admin',
  },
  {
    id: 'admin-logs',
    path: '/AdminPanel/logs',
    domain: 'admin',
    access: 'free',
    roles: ['admin'],
    platform: 'web-only',
    layout: 'admin',
  },
  {
    id: 'admin-subscriptions',
    path: '/AdminPanel/subscriptions',
    domain: 'admin',
    access: 'free',
    roles: ['admin'],
    platform: 'web-only',
    layout: 'admin',
  },
  {
    id: 'admin-roles',
    path: '/AdminPanel/roles',
    domain: 'admin',
    access: 'free',
    roles: ['admin'],
    platform: 'web-only',
    layout: 'admin',
  },
  {
    id: 'admin-invites',
    path: '/AdminPanel/invites',
    domain: 'admin',
    access: 'free',
    roles: ['admin'],
    platform: 'web-only',
    layout: 'admin',
  },
  {
    id: 'admin-settings',
    path: '/AdminPanel/settings',
    domain: 'admin',
    access: 'free',
    roles: ['admin'],
    platform: 'web-only',
    layout: 'admin',
  },
  {
    id: 'admin-analytics',
    path: '/AdminPanel/analytics',
    domain: 'admin',
    access: 'free',
    roles: ['admin'],
    platform: 'web-only',
    layout: 'admin',
  },
  {
    id: 'admin-moderation',
    path: '/AdminPanel/moderation',
    domain: 'admin',
    access: 'free',
    roles: ['admin'],
    platform: 'web-only',
    layout: 'admin',
  },
  {
    id: 'admin-waitlist',
    path: '/AdminPanel/waitlist',
    domain: 'admin',
    access: 'free',
    roles: ['admin'],
    platform: 'web-only',
    layout: 'admin',
  },
  {
    id: 'admin-influencers',
    path: '/AdminPanel/influencers',
    domain: 'admin',
    access: 'free',
    roles: ['admin'],
    platform: 'web-only',
    layout: 'admin',
  },
  {
    id: 'admin-impersonation',
    path: '/AdminPanel/view-as/:userId',
    domain: 'admin',
    access: 'free',
    roles: ['admin'],
    platform: 'web-only',
    layout: 'none',
  },

  // --- Professional Domain ---
  {
    id: 'coach-dashboard',
    path: '/coach-dashboard',
    domain: 'professional',
    access: 'free',
    roles: ['coach', 'admin'],
    platform: 'web-only',
    layout: 'app',
  },
  {
    id: 'coach-students',
    path: '/coach/students',
    domain: 'professional',
    access: 'free',
    roles: ['coach', 'admin'],
    platform: 'web-only',
    layout: 'app',
  },
  {
    id: 'coach-student-profile',
    path: '/coach/student/:id',
    domain: 'professional',
    access: 'free',
    roles: ['coach', 'admin'],
    platform: 'web-only',
    layout: 'app',
  },
  {
    id: 'coach-prescribe-workout',
    path: '/coach/prescribe-workout/:studentId',
    domain: 'professional',
    access: 'free',
    roles: ['coach', 'admin'],
    platform: 'web-only',
    layout: 'app',
  },
  {
    id: 'nutritionist-dashboard',
    path: '/nutritionist-dashboard',
    domain: 'professional',
    access: 'free',
    roles: ['nutritionist', 'admin'],
    platform: 'web-only',
    layout: 'app',
  },
  {
    id: 'nutritionist-clients',
    path: '/nutritionist/clients',
    domain: 'professional',
    access: 'free',
    roles: ['nutritionist', 'admin'],
    platform: 'web-only',
    layout: 'app',
  },
  {
    id: 'nutritionist-client-profile',
    path: '/nutritionist/client/:id',
    domain: 'professional',
    access: 'free',
    roles: ['nutritionist', 'admin'],
    platform: 'web-only',
    layout: 'app',
  },
  {
    id: 'nutritionist-prescribe-diet',
    path: '/nutritionist/prescribe-diet/:clientId',
    domain: 'professional',
    access: 'free',
    roles: ['nutritionist', 'admin'],
    platform: 'web-only',
    layout: 'app',
  },
  {
    id: 'clinician-dashboard',
    path: '/clinician-dashboard',
    domain: 'professional',
    access: 'free',
    roles: ['clinician', 'admin'],
    platform: 'web-only',
    layout: 'app',
  },
  {
    id: 'clinician-patients',
    path: '/clinician/patients',
    domain: 'professional',
    access: 'free',
    roles: ['clinician', 'admin'],
    platform: 'web-only',
    layout: 'app',
  },
  {
    id: 'clinician-patient-profile',
    path: '/clinician/patient/:id',
    domain: 'professional',
    access: 'free',
    roles: ['clinician', 'admin'],
    platform: 'web-only',
    layout: 'app',
  },

  // --- Misc Domain ---
  {
    id: 'calendar',
    path: '/calendar',
    domain: 'misc',
    access: 'premium',
    roles: ['athlete'],
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'integrations',
    path: '/integrations',
    domain: 'misc',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'app',
  },
  {
    id: 'checkout',
    path: '/checkout',
    domain: 'misc',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'waitlist',
    path: '/waitlist',
    domain: 'misc',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'welcome-back',
    path: '/welcome-back',
    domain: 'misc',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'story-landing',
    path: '/start',
    domain: 'misc',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'share-target',
    path: '/share-target',
    domain: 'misc',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'native-only',
    layout: 'none',
  },
  {
    id: 'page-not-found',
    path: '*',
    domain: 'misc',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },

  // --- Monetization ---
  {
    id: 'upgrade',
    path: '/upgrade',
    domain: 'misc',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
    legacyAliases: ['/upgrade-prompts'],
  },
  {
    id: 'billing',
    path: '/billing',
    domain: 'profile',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'restore-purchases',
    path: '/restore-purchases',
    domain: 'misc',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'trial-start',
    path: '/trial',
    domain: 'misc',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'trial-info',
    path: '/trial-info',
    domain: 'misc',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'discounts',
    path: '/discounts',
    domain: 'misc',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },

  // --- App Shell ---
  {
    id: 'explore',
    path: '/explore',
    domain: 'social',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },
  {
    id: 'activity',
    path: '/activity',
    domain: 'social',
    access: 'free',
    roles: ALL_ROLES,
    platform: 'all',
    layout: 'none',
  },

  // --- Guides ---
  {
    id: 'guide-getting-started',
    path: '/guides/getting-started',
    domain: 'support',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'guide-workout-logging',
    path: '/guides/workout-logging',
    domain: 'support',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'guide-plan-vs-execution',
    path: '/guides/plan-vs-execution',
    domain: 'support',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'guide-ai-workout-generation',
    path: '/guides/ai-workout-generation',
    domain: 'support',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'guide-ai-plan-building',
    path: '/guides/ai-plan-building',
    domain: 'support',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'guide-adjusting-plans',
    path: '/guides/adjusting-plans',
    domain: 'support',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'guide-ai-vs-manual',
    path: '/guides/ai-vs-manual',
    domain: 'support',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'guide-progress-photos',
    path: '/guides/progress-photos',
    domain: 'support',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'guide-export-reports',
    path: '/guides/export-reports',
    domain: 'support',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'guide-nutrition-tracking',
    path: '/guides/nutrition-tracking',
    domain: 'support',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'guide-mobile-workouts',
    path: '/guides/mobile-workouts',
    domain: 'support',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'guide-account-settings',
    path: '/guides/account-settings',
    domain: 'support',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
  {
    id: 'guide-coach-management',
    path: '/guides/coach-management',
    domain: 'support',
    access: 'public',
    roles: ALL_ROLES,
    platform: 'web-only',
    layout: 'marketing',
  },
];

export const OVERLAYS: OverlayEntry[] = [
  { id: 'coach-chat', domain: 'professional', access: 'premium' },
  { id: 'food-scanner', domain: 'nutrition', access: 'premium' },
  { id: 'ai-assistant', domain: 'misc', access: 'premium' },
  { id: 'start-fresh-modal', domain: 'misc', access: 'free' },
  { id: 'nutrition-mode-selector', domain: 'nutrition', access: 'premium' },
  { id: 'milestone-system', domain: 'social', access: 'free' },
  { id: 'quick-add', domain: 'dashboard', access: 'premium' },
  { id: 'search-overlay', domain: 'social', access: 'free' },
];
